### ISSUE TITLE
Complete CSS

### ISSUE THREAD

**Issue by ImmaZoni** [autonomys/subspace-docs#1]
The current CSS is very minimal. Some things we could improve are the following. 

- [ ] Implement full style guide colors from Figma.
- [ ] Add Grey shading to help with light mode.
- [x] Adjust Colors for dark mode. (Purple is a little too dark, etc)
- [x] Add Inverted branding for dark mode (white logo, etc)
- [ ] Add Montserrat and open sans fonts to match style guide.

**Comment by vexr** [comment]
Do the first two points still need attention? I don't see any obvious issues that need to be addressed, and it seems the final point has already been resolved. If there are no outstanding issues, can we close this?
