### ISSUE TITLE
Add direction for what to do after farmer has started

### ISSUE THREAD

**Issue by ImmaZoni** [autonomys/subspace-docs#134]
We should add an additional step at the end of the documentation to show where users can check their nodes and such. 

Add Telemetry Link
Add Explorer Link
Add subscan link

just to prompt the user to know how to check their farmer.

**Comment by vexr** [comment]
I recommend closing this issue, as these resources are included in the `Tips & Tricks` section under Advanced CLI. If that is not suitable, I can add these resources as an admonition in a more appropriate location.
