### ISSUE TITLE
Update docs regarding supporting advanced substrate options

### ISSUE THREAD

**Issue by ozgunozerk** [autonomys/subspace-docs#163]
### What is the feature you would like to see?

We have added support for overwriting substrate options for node. Docs should be updated accordingly

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vexr** [comment]
I recommend closing this issue, as all parameters are included in the binaries' `--help` option. The intention appears to be that the default settings are sufficient for most farmers to get started. Adding all these options to the documentation would require constant updates to both the binaries and the documentation whenever these advanced parameters change. From my perspective, if this information should still be included, the only necessary addition would be an admonition highlighting the `--help` option.

**Comment by jim-counter** [comment]
If we do not have any guidance on using `--help` we should definitely add it.

**Comment by jim-counter** [comment]
Admonition added to docs here: https://github.com/autonomys/subspace-docs/pull/662
