### ISSUE TITLE
Clarify minimum CPU requirements

### ISSUE THREAD

**Issue by ImmaZoni** [autonomys/subspace-docs#172]
It seems we need to be clearer on our minimum system specifications, we currently show a rough year estimation for cpu support but this is leading to some confusion. 

See this forum post for more context from nazar

https://forum.subspace.network/t/illegal-instruction-core-dumped/1348/10
```[tasklist]
### Tasks
- [ ] Operator's requirements?
- [ ] Clarify staking requirements?
```

**Comment by vexr** [comment]
I suggest closing this issue, as this information is already included in the [prerequisites](https://docs.autonomys.xyz/docs/farming-&-staking/farming/prerequisites) section of the documentation.
