### ISSUE TITLE
Include a section covering common errors

### ISSUE THREAD

**Issue by EmilFattakhov** [autonomys/subspace-docs#193]
There are a few types of logs for the CLI that sometimes gets interpreted as bugs
Elaborate on what kind of errors are breaking and what errors can be ignored

Use Subspace [Discord](https://discord.gg/subspace-network) and [Forum ](https://forum.subspace.network/) for an inspiration

**Comment by EmilFattakhov** [comment]
Addressed in [PR 197](https://github.com/subspace/subspace-docs/pull/197)

But keeping the issue open for now, in case anyone sees some missing common problem, or any other improvements to the Common Problems page.

**Comment by vexr** [comment]
> Addressed in [PR 197](https://github.com/subspace/subspace-docs/pull/197)
> 
> But keeping the issue open for now, in case anyone sees some missing common problems, or any other improvements to the Common Problems page.

Perhaps we should remove some of the older [common problems](https://docs.autonomys.xyz/docs/farming-&-staking/farming/common_problems) that are no longer relevant due to software updates. There are still references to `Gemini 3e.`
