### ISSUE TITLE
The interface enlarges when some languages are selected

### ISSUE THREAD

**Issue by extSunset** [autonomys/subspace-docs#217]
Tested with Russian and Ukrainian. The interface is very much enlarged, even in the absence of translation as such.

**Comment by PurpleM0ney** [comment]
![image](https://github.com/subspace/subspace-docs/assets/108991469/9fc5f912-7d71-4119-ab2b-c9a8c5c004e1)


That's strange, in my case it's fine. Could you please provide a link to a page where a similar problem is observed?

**Comment by EmilFattakhov** [comment]
I also couldn't find any pages with the enlarged content. I suggest to keep this issue open for now and keep an eye on it.

**Comment by EmilFattakhov** [comment]
That's valuable feedback, thank you @extSunset! We should look into what works incorrectly in Firefox and non-Chromium engines.

**Comment by vexr** [comment]
I suggest closing this issue, as rendering problems no longer seem to occur on Firefox, and there has been no discussion about this happening for quite some time.
