### ISSUE TITLE
Add documentation for `open-logs` command in the troubleshooting section

### ISSUE THREAD

**Issue by ImmaZoni** [autonomys/subspace-docs#239]
**Description:**

The Pulsar project offers a handy `open-logs` command that opens the log directory directly in the OS's file explorer. This feature can be extremely useful for users when troubleshooting issues. However, it seems this command is not yet documented in our troubleshooting section.

**Task:**
- [ ] Add a description and usage example of the `open-logs` command to the troubleshooting section of our documentation.
- [ ] Mention any common scenarios/usecases where this command might be particularly useful.

**Additional Information:**
- This can be a great opportunity for community members who are new to the project or looking for a 'good first issue' to tackle.
- For reference or any questions, please feel free to comment and discuss

**Comment by vexr** [comment]
I suggest closing this issue, as Pulsar has been deprecated in favor of Space Acres.
