### ISSUE TITLE
Refine Header Navigation for Documentation Sections

### ISSUE THREAD

**Issue by ImmaZoni** [autonomys/subspace-docs#252]
**Description**:
Currently, both the `Docs` and `Developer Docs` headers are simultaneously highlighted when navigating into any of their subsections. To enhance user experience and clarity:

- Propose introducing a unified dropdown titled `Documentation`.
- This dropdown can list `Developer Docs` and `Farming Docs` as selectable options.

This change will streamline the header and ensure only the relevant section is highlighted during navigation.

![image](https://github.com/subspace/subspace-docs/assets/31865152/40b28504-f89d-4eeb-a822-9b66bd36974a)

**Comment by vexr** [comment]
This no longer appears to be an issue that requires attention.
