### ISSUE TITLE
Refactor Service File Generators for Better Maintainability

### ISSUE THREAD

**Issue by ImmaZoni** [autonomys/subspace-docs#306]
**Description**:
The current implementation of both the Systemd Service File Generator and the Docker File Generator embeds their templates directly within the `index.jsx` of their respective components. This approach, while functional, poses challenges in maintaining and updating the templates.

**Proposal**:
To enhance maintainability and allow for easier updates, especially by non-developers, I recommend refactoring the components. We should externalize the templates into dedicated files, namely `SystemdTemplate` and `DockerComposeTemplate`. 

**Benefits**:
- **Separation of Concerns**: By decoupling the templates from the core logic, we reinforce the principle of separation of concerns.
- **Ease of Update**: Non-technical contributors can easily view and modify the templates without the risk of inadvertently breaking the core functionality.
- **Enhanced Collaboration**: This setup would foster a collaborative environment where users can contribute to the template's improvement without delving into the component logic.

I'm eager to gather feedback from the community on this suggestion. Your insights would be invaluable as we strive for continuous improvement! 😄

---

**Comment by EmilFattakhov** [comment]
The corresponding improvements have been made to both generators to ensure their maintainability.
