### ISSUE TITLE
Update Operator Guide to Reflect Use of Precompiled Binaries for Key Generation

### ISSUE THREAD

**Issue by ImmaZoni** [autonomys/subspace-docs#312]
**Description**:
The operator guide's command examples currently assume that users have built the software from source. This may not reflect the typical user's experience, as many will download and use precompiled binaries. To better serve this user base, it's crucial to update the command examples to reference precompiled binaries rather than source-compiled ones.

**Current Command**:
```
target/production/subspace-node key generate --scheme sr25519
```

**Proposed Update**:
```
.\subspace-node-windows-x86_64-skylake-gemini-3g-2023-oct-31.exe key generate --scheme sr25519
```

**Additional Context**:
The above example is just one instance. Many commands in the guide reference the `target/production/subspace-node` binary. It's imperative to review and update all such instances in the documentation to ensure consistency and accuracy.

*Note*: While the provided example is for the Windows binary, the idea applies universally. Updates should be considered for all platform-specific binaries in the guide.

Curious your thoughts @EmilFattakhov & @jim-counter

**Comment by jim-counter** [comment]
Sounds sensible to me.

**Comment by vexr** [comment]
I recommend closing this issue, as the updated method has already been [provided](https://docs.autonomys.xyz/docs/farming-&-staking/staking/operators/register-operator#create-operator-key).
