### ISSUE TITLE
Add Unofficial Chinese Telegram Group to Community Page

### ISSUE THREAD

**Issue by ImmaZoni** [autonomys/subspace-docs#313]
**Description**:
A community member has initiated an unofficial Chinese Telegram group for Subspace. To foster inclusivity and reach out to our Chinese-speaking audience, it would be beneficial to include this link on our official community page.

**Telegram Group Link**:
[Subspace Chinese Telegram Group](https://t.me/subspacecn/1)

**Recommendation**:
While the group is unofficial, we should clearly indicate this status when listing it on the community page to ensure transparency.

**Comment by jim-counter** [comment]
Sounds sensible @vexr. Let's close this one down in favour of that approach.
