### ISSUE TITLE
Some Chinese translation errors But I did not find the corresponding parameters in https://crowdin.com/project/subspace-docs. Maybe crowdin has not been updated. Please update the translation

### ISSUE THREAD

**Issue by Allen9168** [autonomys/subspace-docs#378]
Some Chinese translation errors
But I did not find the corresponding parameters in https://crowdin.com/project/subspace-docs. Maybe crowdin has not been updated.
Please update the translation

**Comment by jim-counter** [comment]
@ImmaZoni please take a look at this.

**Comment by vexr** [comment]
I recommend closing this issue unless there is a still a specific translation error that needs to be addressed.
