### ISSUE TITLE
Can you describe typical bandwidth usage for this? 

### ISSUE THREAD

**Issue by Motophan** [autonomys/subspace-docs#579]
```
Make sure you have a stable network connection. During the plotting phase of farming, it can be network intensive.

This may impact your network usage so please check your network connection if you have a hard data limit.
```

This is unclear, is this 100GB/m? 1TB/m?, 10TB/m? 

Could you estimate
1TB flash storage = XGB of bandwidth used?

**Comment by jim-counter** [comment]
@nazar-pc is an estimation here possible at all? I expect there are too many variables to set an accurate expectation?

@randywessels is this something you monitor on your setup?

Discord could be the best place to canvass bandwidth usage to get a feel for example real-world usage statistics.

**Comment by nazar-pc** [comment]
It is not possible to have such estimation. There are multiple factors and it would not help much if I explain all of them.
Users should have 10 Mbps+ reliable unmetered connection. If connection is metered you probably shouldn't run the software.
