### ISSUE TITLE
Update ext4 formatting options

### ISSUE THREAD

**Issue by nazar-pc** [autonomys/subspace-docs#770]
We should add `-C 16384 -O bigalloc` to the ext4 formatting options.

`16384` is the native page size on most modern SSDs, forcing file system to use it instead of inferred 512 or 4096 will improve performance and reduce write amplification.

Something new I learned today :slightly_smiling_face:

**Comment by jim-counter** [comment]
Fixed in https://github.com/autonomys/subspace-docs/pull/774.
